### ISSUE TITLE
Reference to 'strcat' in Mutable borrows task

### ISSUE THREAD

**Issue by raventid** [nikomatsakis/intorust#8]
At the bottom of a code sample you can find this text ->  "// Question: Now that you've converted `strcat`, what happens if you". In http://intorust.com/hint/mutable_borrow_1/ there is a new signature of join_words function, but I did not use the hint, so I had no idea why do we call it strcat)) Perhaps just leave it as 'join_words'?

[The link](https://play.rust-lang.org/?code=pub+fn+main%28%29+%7B%0A++++let+%28mut+str1%2C+str2%29+%3D+two_words%28%29%3B%0A++++str1+%3D+join_words%28str1%2C+str2%29%3B%0A++++println%21%28%22concatenated+string+is+%7B%3A%3F%7D%22%2C+str1%29%3B%0A%7D%0A%0Afn+two_words%28%29+-%3E+%28String%2C+String%29+%7B%0A++++%28format%21%28%22fellow%22%29%2C+format%21%28%22Rustaceans%22%29%29%0A%7D%0A%0A%2F%2F%2F+Concatenate+%60suffix%60+onto+the+end+of+%60prefix%60.%0Afn+join_words%28mut+prefix%3A+String%2C+suffix%3A+String%29+-%3E+String+%7B%0A++++prefix.push%28%27+%27%29%3B+%2F%2F+separate+the+words+with+a+space%0A++++for+ch+in+suffix.chars%28%29+%7B%0A++++++++prefix.push%28ch%29%3B%0A++++%7D%0A++++prefix%0A%7D%0A%0A%2F%2F+Challenge%3A+Convert+%60join_words%60+to+use+borrowing%2C+not+ownership.%0A%2F%2F+The+new+function+should+mutate+%60prefix%60+in+place%2C+and+should+not%0A%2F%2F+take+ownership+of+%60suffix%60.%0A%2F%2F%0A%2F%2F+Hint%3A+If+you%27d+like+a+hint+as+to+how+to+proceed%2C+open%0A%2F%2F+%3Chttp%3A%2F%2Fintorust.com%2Fhint%2Fmutable_borrow_1%2F%3E.%0A%0A%2F%2F+Question%3A+Now+that+you%27ve+converted+%60strcat%60%2C+what+happens+if+you%0A%2F%2F+call+%60strcat%60+using+the+same+string+for+%60prefix%60+and+%60suffix%60%3F%0A%2F%2F+Why%3F%0A&version=nightly)

P.S. Very nice tutorial, thank you! But, please, don't sing :pray:

**Comment by nikomatsakis** [comment]
Thanks! Fixed.

> P.S. Very nice tutorial, thank you! But, please, don't sing 🙏 

No promises. ;)

**Comment by k4rtik** [comment]
Haha, I like the singing, especially because it adds a fun element when I am watching at 2x speed.

Yeah, great set of tutorials Niko. Looking forward to more.
